lista_estilos = [
                "alphonse mucha style",
                 "alphonse mucha style", 
                 "comic",
                 "art nouveau",
                 "art nouveau",                    
                 "watercolor",                  
                 "watercolor",
                 "watercolor",
                 "watercolor",
                 "watercolor",
                 "watercolor",
                 "watercolor",
                 "watercolor",
                 "watercolor",
                 "painting",
                 "painting", 
                 "anime",
                 "anime", 
                 "anime", 
                 "anime", 
                 "anime",  
                 "manga",
                 "manga",
                 "manga",
                 ]
